### ISSUE TITLE
Center x in clear button

### ISSUE THREAD

**Issue by btxtiger** [wp126/Digital-Signature-For-Contact-Form-7#3]
If you add `padding-bottom: 3px;` to the clear button css, the x will be centered.
<img width="335" alt="image" src="https://github.com/wp126/Digital-Signature-For-Contact-Form-7/assets/15804690/eae10061-9e44-4610-bafe-60b46e21bc90">
<img width="331" alt="image" src="https://github.com/wp126/Digital-Signature-For-Contact-Form-7/assets/15804690/b7c8eaa9-4ecc-42eb-b00b-4b3267519e12">

```css
.dscf7_signature input.clearButton {
    padding-bottom: 3px;
}
```
